"use client";

import { FormEvent, useEffect, useState } from "react";
import { AdminLoading, AdminSignInRequired } from "../../components/admin-auth-state";
import { AdminShell } from "../../components/admin-shell";
import { BusinessType, createBusinessType, deleteBusinessType, listBusinessTypes, updateBusinessType } from "../../lib/api";
import { useAdminSession } from "../../lib/use-admin-session";

type Form = { code: string; name: string; description: string; is_active: boolean };
const empty: Form = { code: "", name: "", description: "", is_active: true };

export default function BusinessTypesPage() {
  const { session, ready, withAuth } = useAdminSession();
  const [items, setItems] = useState<BusinessType[]>([]); const [form, setForm] = useState<Form>(empty); const [editing, setEditing] = useState<BusinessType | null>(null); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!session) return; void withAuth((token) => listBusinessTypes(token)).then((result) => setItems(result.data)).catch((cause: Error) => setError(cause.message)); }, [session, withAuth]);
  function close() { setEditing(null); setForm(empty); setShow(false); }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { if (editing) { const result = await withAuth((token) => updateBusinessType(token, editing.id, { name: form.name.trim(), description: form.description.trim(), is_active: form.is_active })); setItems((current) => current.map((item) => item.id === editing.id ? result.data : item)); } else { const result = await withAuth((token) => createBusinessType(token, { code: form.code.trim().toUpperCase(), name: form.name.trim(), description: form.description.trim(), is_active: form.is_active })); setItems((current) => [...current, result.data].sort((a, b) => a.name.localeCompare(b.name))); } close(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save the business type."); } finally { setBusy(false); } }
  async function remove(item: BusinessType) { if (!window.confirm(`Delete ${item.name}?`)) return; setBusy(true); setError(""); try { await withAuth((token) => deleteBusinessType(token, item.id)); setItems((current) => current.filter((value) => value.id !== item.id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to delete the business type."); } finally { setBusy(false); } }
  if (!ready) return <AdminLoading />; if (!session) return <AdminSignInRequired />;
  return <AdminShell session={session} active="business-types"><header className="topbar"><div><p className="eyebrow">PLATFORM REFERENCE DATA</p><h1>Business types</h1><p className="muted">Define the business types that can be assigned to shops.</p></div><button className="outline-button" disabled={busy} onClick={() => { setForm(empty); setEditing(null); setShow(true); }}>+ Add business type</button></header>{error && <p className="error banner">{error}</p>}<section className="panel route-panel"><div className="panel-heading"><div><p className="eyebrow">BUSINESS TYPE DIRECTORY</p><h2>{items.length} business types</h2></div></div><div className="data-list">{items.map((item) => <div className="data-row" key={item.id}><span className="currency-symbol">{item.name[0]?.toUpperCase()}</span><span className="data-info"><strong>{item.name}</strong><small>{item.code}{item.description ? ` · ${item.description}` : ""}</small></span><span className={`pill ${item.is_active ? "success" : "danger"}`}>{item.is_active ? "Active" : "Inactive"}</span><button className="row-action" disabled={busy} onClick={() => { setEditing(item); setForm({ code: item.code, name: item.name, description: item.description, is_active: item.is_active }); setShow(true); }}>Edit</button><button className="row-action danger-text" disabled={busy} onClick={() => void remove(item)}>Delete</button></div>)}{items.length === 0 && <p className="empty">No business types are configured.</p>}</div></section>{show && <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="panel-heading"><div><p className="eyebrow">BUSINESS TYPE</p><h2>{editing ? "Edit business type" : "Add business type"}</h2></div><button type="button" className="close" onClick={close}>×</button></div><label>Code<input required disabled={Boolean(editing)} value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase() })} /></label><label>Name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Description (optional)<textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label>Status<select value={form.is_active ? "active" : "inactive"} onChange={(event) => setForm({ ...form, is_active: event.target.value === "active" })}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button disabled={busy}>{busy ? "Saving…" : editing ? "Save changes" : "Create business type"}</button></form></div>}</AdminShell>;
}
