ALTER TABLE shops ADD COLUMN IF NOT EXISTS footer_note TEXT NOT NULL DEFAULT '';
ALTER TABLE payment_settings ADD COLUMN IF NOT EXISTS tax_label VARCHAR(100) NOT NULL DEFAULT 'Tax';
ALTER TABLE payment_settings ADD COLUMN IF NOT EXISTS receipt_note TEXT NOT NULL DEFAULT '';
